# Generated by Django 3.1.5 on 2021-01-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_auto_20210115_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
